<?php

namespace Blog\Repository;

use Blog\Application;
use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository (finds the addresses / branches of a company)
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{

	public function findCompanyAddresses($companyId)
	{
		$results = $this->createQueryBuilder('a')
				->select('a')
				->where('a.company = :company_id')
				->orderBy('a.country', 'DESC')
				->setParameter('company_id', $companyId)
				->getQuery()
				->getResult();

		foreach($results as $result)
		{
			$addresses[$result->getId()] = [
				'id' => $result->getId(),
				'country' => $result->getCountry(),
				'region' => $result->getRegion(),
				'city' => $result->getCity(),
				'street' => $result->getStreet(),
				'postCode' => $result->getPostCode()
			];	
		}
		return $addresses;
	}
}
