<?php 

namespace Blog\Repository;

use Blog\Application;
use Doctrine\ORM\EntityRepository;

/**
 * ProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessCategoryRepository extends EntityRepository
{

}